# service config
server:
  port: 8099
  servlet:
    context-path: /


spring:
  application:
    name: virgo
  datasource:
    url: jdbc:mysql://192.168.25.23:3306/sub?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: anKVdm2e
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root


feign:
  httpclient:
    enabled: false
    max-connections: 200
    max-connections-per-route: 50
    time-to-live: 600
    time-to-live-unit: seconds
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 7000
  hystrix:
    enabled: false
