# service config
server:
  port: 8099
  servlet:
    context-path: /


spring:
  application:
    name: virgo
  datasource:
    url: jdbc:mysql://192.168.25.23:3306/sub?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: anKVdm2e
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root